// Generated by CoffeeScript 1.6.3
module("Test The Creation of CodeMirror Plugin");

test("If Plugin Is Loaded Into JQuery", function() {
  return ok(typeof $.fn.codemirror === "function", "CodeMirror Plugin Is Loaded");
});

module("Test The Operation Of The CodeMirror Plugin");

test("Test If Code Mirror Object Is Returned", function() {
  var oV1;
  oV1 = $("textarea.codestart").codemirror({
    lineNumbers: true,
    matchBrackets: true,
    theme: 'neat'
  });
  equal(typeof oV1, "object", "Object Returned");
  return ok(oV1 instanceof CodeMirror, "Object Instance Of CodeMirror");
});

module("Test The Custom Set Data Properties");

test("Test If Code Mirror Object has linenumbers set to false", function() {
  var oV1;
  oV1 = $("textarea.codestart").codemirror();
  return equal(oV1.getOption("lineNumbers"), false, "Line Number Set To False");
});

test("Test If Code Mirror Object Mode is Declared To xml", function() {
  var oV1;
  oV1 = $("textarea.codestart").codemirror();
  return equal(oV1.getOption("mode"), "xml", "Code Mirror Object Is Set To xml");
});
